services:

  api:
    build: 
      context: .
      dockerfile: Dockerfile.api
    container_name: fastapi_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./:/app

  worker:
    build: 
      context: .
      dockerfile: Dockerfile.worker
    container_name: worker_app
    command: python -m app.worker.worker
    environment:
      - WHISPER_MODEL=tiny
    depends_on:
      - redis
    volumes:
      - ./:/app

  redis:
    image: redis:7
    container_name: redis_server
    ports:
      - "6379:6379"
