"""initial migration

Revision ID: 569437776e60
Revises: 
Create Date: 2026-04-06 08:07:56.056194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '569437776e60'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aianalysis_chat_session_id'), table_name='aianalysis')
    op.drop_index(op.f('ix_aianalysis_recording_id'), table_name='aianalysis')
    op.drop_table('aianalysis')
    op.drop_index(op.f('ix_chatmessage_chat_session_id'), table_name='chatmessage')
    op.drop_table('chatmessage')
    op.drop_index(op.f('ix_analysis_attempt_id'), table_name='analysis')
    op.drop_index(op.f('ix_analysis_primary_training_mode'), table_name='analysis')
    op.drop_table('analysis')
    op.drop_index(op.f('ix_chatsession_is_active'), table_name='chatsession')
    op.drop_index(op.f('ix_chatsession_recording_id'), table_name='chatsession')
    op.drop_index(op.f('ix_chatsession_user_id'), table_name='chatsession')
    op.drop_table('chatsession')
    op.drop_index(op.f('ix_attempts_is_final_attempt'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_parent_attempt_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_question_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_recording_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_training_mode'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_user_id'), table_name='attempts')
    op.drop_table('attempts')
    op.drop_index(op.f('ix_recording_question_id'), table_name='recording')
    op.drop_index(op.f('ix_recording_user_id'), table_name='recording')
    op.drop_table('recording')
    op.drop_index(op.f('ix_ai_usage_usage_date'), table_name='ai_usage')
    op.drop_index(op.f('ix_ai_usage_user_id'), table_name='ai_usage')
    op.drop_table('ai_usage')
    op.drop_index(op.f('ix_user_progress_last_training_mode'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_user_id'), table_name='user_progress')
    op.drop_table('user_progress')
    op.drop_index(op.f('ix_request_logs_endpoint'), table_name='request_logs')
    op.drop_index(op.f('ix_request_logs_timestamp'), table_name='request_logs')
    op.drop_index(op.f('ix_request_logs_user_id'), table_name='request_logs')
    op.drop_table('request_logs')
    op.drop_index(op.f('ix_training_followups_training_mode'), table_name='training_followups')
    op.drop_table('training_followups')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_question_day_unlock'), table_name='question')
    op.drop_index(op.f('ix_question_title'), table_name='question')
    op.drop_table('question')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey'))
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('training_followups',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('training_mode', postgresql.ENUM('delivery_training', 'structure_training', 'behavioral_training', name='trainingmode'), autoincrement=False, nullable=False),
    sa.Column('question_text', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('difficulty_level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('training_followups_pkey'))
    )
    op.create_index(op.f('ix_training_followups_training_mode'), 'training_followups', ['training_mode'], unique=False)
    op.create_table('request_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('endpoint', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('request_logs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('request_logs_pkey'))
    )
    op.create_index(op.f('ix_request_logs_user_id'), 'request_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_request_logs_timestamp'), 'request_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_request_logs_endpoint'), 'request_logs', ['endpoint'], unique=False)
    op.create_table('attempts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recording_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('parent_attempt_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transcript', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('training_mode', postgresql.ENUM('delivery_training', 'structure_training', 'behavioral_training', name='trainingmode'), autoincrement=False, nullable=False),
    sa.Column('analysis_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('detected_issues', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('recommendations', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('is_final_attempt', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['parent_attempt_id'], ['attempts.id'], name=op.f('attempts_parent_attempt_id_fkey')),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name=op.f('attempts_question_id_fkey')),
    sa.ForeignKeyConstraint(['recording_id'], ['recording.id'], name=op.f('attempts_recording_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('attempts_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('attempts_pkey'))
    )
    op.create_index(op.f('ix_attempts_user_id'), 'attempts', ['user_id'], unique=False)
    op.create_index(op.f('ix_attempts_training_mode'), 'attempts', ['training_mode'], unique=False)
    op.create_index(op.f('ix_attempts_recording_id'), 'attempts', ['recording_id'], unique=False)
    op.create_index(op.f('ix_attempts_question_id'), 'attempts', ['question_id'], unique=False)
    op.create_index(op.f('ix_attempts_parent_attempt_id'), 'attempts', ['parent_attempt_id'], unique=False)
    op.create_index(op.f('ix_attempts_is_final_attempt'), 'attempts', ['is_final_attempt'], unique=False)
    op.create_table('analysis',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('attempt_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('raw_analysis_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('primary_training_mode', postgresql.ENUM('delivery_training', 'structure_training', 'behavioral_training', name='trainingmode'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], name=op.f('analysis_attempt_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('analysis_pkey'))
    )
    op.create_index(op.f('ix_analysis_primary_training_mode'), 'analysis', ['primary_training_mode'], unique=False)
    op.create_index(op.f('ix_analysis_attempt_id'), 'analysis', ['attempt_id'], unique=True)
    op.create_table('user_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_attempts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('final_attempts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('delivery_training_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('structure_training_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('behavioral_training_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('average_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('best_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('last_training_mode', postgresql.ENUM('delivery_training', 'structure_training', 'behavioral_training', name='trainingmode'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('user_progress_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_progress_pkey'))
    )
    op.create_index(op.f('ix_user_progress_user_id'), 'user_progress', ['user_id'], unique=True)
    op.create_index(op.f('ix_user_progress_last_training_mode'), 'user_progress', ['last_training_mode'], unique=False)
    op.create_table('ai_usage',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('usage_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('ai_requests_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('voice_requests_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tokens_used', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('ai_usage_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_usage_pkey'))
    )
    op.create_index(op.f('ix_ai_usage_user_id'), 'ai_usage', ['user_id'], unique=False)
    op.create_index(op.f('ix_ai_usage_usage_date'), 'ai_usage', ['usage_date'], unique=False)
    op.create_table('chatsession',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recording_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['recording_id'], ['recording.id'], name=op.f('chatsession_recording_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('chatsession_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('chatsession_pkey'))
    )
    op.create_index(op.f('ix_chatsession_user_id'), 'chatsession', ['user_id'], unique=False)
    op.create_index(op.f('ix_chatsession_recording_id'), 'chatsession', ['recording_id'], unique=False)
    op.create_index(op.f('ix_chatsession_is_active'), 'chatsession', ['is_active'], unique=False)
    op.create_table('recording',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('audio_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name=op.f('recording_question_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('recording_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('recording_pkey'))
    )
    op.create_index(op.f('ix_recording_user_id'), 'recording', ['user_id'], unique=False)
    op.create_index(op.f('ix_recording_question_id'), 'recording', ['question_id'], unique=False)
    op.create_table('chatmessage',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chat_session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sender_type', postgresql.ENUM('user', 'ai', name='sendertype'), autoincrement=False, nullable=False),
    sa.Column('message_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('audio_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chatsession.id'], name=op.f('chatmessage_chat_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('chatmessage_pkey'))
    )
    op.create_index(op.f('ix_chatmessage_chat_session_id'), 'chatmessage', ['chat_session_id'], unique=False)
    op.create_table('aianalysis',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chat_session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recording_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('summary', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('feedback', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tips', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chatsession.id'], name=op.f('aianalysis_chat_session_id_fkey')),
    sa.ForeignKeyConstraint(['recording_id'], ['recording.id'], name=op.f('aianalysis_recording_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('aianalysis_pkey'))
    )
    op.create_index(op.f('ix_aianalysis_recording_id'), 'aianalysis', ['recording_id'], unique=True)
    op.create_index(op.f('ix_aianalysis_chat_session_id'), 'aianalysis', ['chat_session_id'], unique=True)
    op.create_table('question',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('day_unlock', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('question_pkey'))
    )
    op.create_index(op.f('ix_question_title'), 'question', ['title'], unique=False)
    op.create_index(op.f('ix_question_day_unlock'), 'question', ['day_unlock'], unique=False)
    # ### end Alembic commands ###
