"""generated for final attempt

Revision ID: c7e6b2dc6c4d
Revises: 9f2d3b7a1a10
Create Date: 2026-04-18 14:25:22.776247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7e6b2dc6c4d'
down_revision: Union[str, Sequence[str], None] = '9f2d3b7a1a10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_logs_endpoint'), table_name='request_logs')
    op.drop_index(op.f('ix_request_logs_timestamp'), table_name='request_logs')
    op.drop_index(op.f('ix_request_logs_user_id'), table_name='request_logs')
    op.drop_table('request_logs')
    op.add_column('attempts', sa.Column('stage', sa.Enum('INITIAL', 'TRAINING', 'FINAL', name='attemptstage'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attempts', 'stage')
    op.create_table('request_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('endpoint', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('request_logs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('request_logs_pkey'))
    )
    op.create_index(op.f('ix_request_logs_user_id'), 'request_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_request_logs_timestamp'), 'request_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_request_logs_endpoint'), 'request_logs', ['endpoint'], unique=False)
    # ### end Alembic commands ###
